APP-611 origin check multiple ips
robson-sanchez/App-Integrations-Core pull request #1
Opened 2017-01-26 18:16 UTC by ecarrenho-daitan

When the x-forwarded-for header contains multiple IP's separated by comma, the request will be accepted if any of the IP's is listed the the allowed origins list.

2017-01-27 16:11 UTC, robson-sanchez approved these changes
Minor changes.

In general, I think we should put the error and warning messages in a separate properties file like a message source. I believe it should be better than define big constants.

Example: https://www.mkyong.com/spring/spring-resource-bundle-with-resourcebundlemessagesource-example/

It doesn't need to be implemented now, but we should consider in the next sprints.

2017-01-27 16:11 UTC, rsanchez-daitan commented on integration-web/src/main/java/org/symphonyoss/integration/web/filter/WebHookOriginCheckFilter.java
> +        LOGGER.warn(ExceptionMessageFormatter.format("Webhook Filter",
"Webhook Filter" should be a constant field to reuse in the class.

2017-01-31 19:02 UTC, ecarrenho-daitan commented on integration-web/src/main/java/org/symphonyoss/integration/web/filter/WebHookOriginCheckFilter.java
> +        LOGGER.warn(ExceptionMessageFormatter.format("Webhook Filter",
Done.

2017-02-01 00:01 UTC, dnsymphony requested changes

2017-02-01 00:01 UTC, dnsymphony commented on integration-web/src/test/java/org/symphonyoss/integration/web/filter/WebHookOriginCheckFilterTest.java
> +  private static final String REMOTE_ADDRESS_LIST_SECOND_IP_ALLOWED = "10.30.224.40, 192.30.252.40";
One of these should verify that the regex will work for IPs that are separated by comma but no space.

2017-02-01 11:49 UTC, ecarrenho-daitan commented on integration-web/src/test/java/org/symphonyoss/integration/web/filter/WebHookOriginCheckFilterTest.java
> +  private static final String REMOTE_ADDRESS_LIST_SECOND_IP_ALLOWED = "10.30.224.40, 192.30.252.40";
Done.

2017-02-01 13:44 UTC, merged