APP-837 / APP-838
robson-sanchez/App-Integrations-Core pull request #24
Opened 2017-03-08 13:28 UTC by rsanchez-daitan

- APP-837 Remove Symphony dependencies from sdk
- APP-838 Remove Symphony dependencies from webcommons

2017-03-08 17:07 UTC, ecarrenho-daitan commented on integration-provisioning/src/main/java/org/symphonyoss/integration/provisioning/client/model/Envelope.java
> + * Wrap the data into an envelope.
Add information here to explain that the Apps Repository API wraps all request and response content in a "data" object and that is the purpose of this wrapper class.

2017-03-08 17:11 UTC, ecarrenho-daitan reviewed
LGTM.

2017-03-08 17:11 UTC, ecarrenho-daitan commented
@dnsymphony please review.

2017-03-08 20:13 UTC, dnsymphony requested changes
Unit tests?

2017-03-08 20:13 UTC, dnsymphony commented on integration-provisioning/src/main/java/org/symphonyoss/integration/provisioning/client/AppRepositoryClient.java
> +  public List getAppsAvailable(String userId) throws AppRepositoryClientException {
Please add javadoc to all methods

2017-03-09 13:00 UTC, rsanchez-daitan commented on integration-provisioning/src/main/java/org/symphonyoss/integration/provisioning/client/model/Envelope.java
> + * Wrap the data into an envelope.
FIXED

2017-03-09 13:33 UTC, rsanchez-daitan commented on integration-provisioning/src/main/java/org/symphonyoss/integration/provisioning/client/AppRepositoryClient.java
> +  public List getAppsAvailable(String userId) throws AppRepositoryClientException {
FIXED

2017-03-09 17:56 UTC, rsanchez-daitan commented
@dnsymphony I addressed the PR's comments and also added some unit tests to the module integration-provisioning.

The missing unit tests will be implemented in my next PR related to the APP-836

Please check again if everything is ok.

2017-03-09 18:02 UTC, dnsymphony approved these changes

2017-03-10 20:06 UTC, rsanchez-daitan commented
I'm gonna open another PR directly on the symphonyoss

2017-03-10 20:06 UTC, closed without merging