APP-649 Report Integration Versions and Configurator Apps Info
robson-sanchez/App-Integrations-Core pull request #6
Opened 2017-02-01 21:05 UTC by rsanchez-daitan

- Health check reports versions for each integration
- Health check reports the configurator app links for icon and configurator app
- Health check reports OK for the integration only if the icon and configurator app links are accessible

2017-02-10 13:09 UTC, cmarcondes-daitan commented on integration-healthcheck/src/main/java/org/symphonyoss/integration/healthcheck/services/CompositeServiceHealthAggregator.java
> +  public Health aggregate(Map<String, Health> healths) {
Maybe you could write javadoc to detail the method

2017-02-10 13:28 UTC, cmarcondes-daitan approved these changes

2017-02-15 12:24 UTC, rsanchez-daitan commented
@dnsymphony could you review it please ?

2017-02-16 00:55 UTC, dnsymphony requested changes

2017-02-16 00:55 UTC, dnsymphony commented on integration-healthcheck/src/main/java/org/symphonyoss/integration/healthcheck/services/ServiceVersion.java
> +public class ServiceVersion implements Comparable<ServiceVersion> {
Did you look for an existing library that models "semantic versioning"?  Something like https://github.com/zafarkhaja/jsemver

2017-02-16 00:55 UTC, dnsymphony commented on integration-healthcheck/src/main/java/org/symphonyoss/integration/healthcheck/services/ServiceHealthIndicator.java
> +        String version = node.path(VERSION).asText();
Does this work for all services?  Shouldn't each implementation of ServiceHealthIndicator be responsible for defining where in the response the version should be found?

2017-02-16 15:52 UTC, rsanchez-daitan commented on integration-healthcheck/src/main/java/org/symphonyoss/integration/healthcheck/services/ServiceVersion.java
> +public class ServiceVersion implements Comparable<ServiceVersion> {
FIXED. Makes sense uses a library instead of creating our own implementation.

2017-02-16 15:57 UTC, rsanchez-daitan commented on integration-healthcheck/src/main/java/org/symphonyoss/integration/healthcheck/services/ServiceHealthIndicator.java
> +        String version = node.path(VERSION).asText();
It works for the current services, but I extracted the code to a method and remained this logic as a default behavior. New services can override this method when required.

2017-02-16 15:57 UTC, rsanchez-daitan commented
@dnsymphony please check again.

2017-02-16 16:19 UTC, dnsymphony approved these changes

2017-02-16 16:22 UTC, merged